apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ printf "%s.%s" .Values.serviceName .Values.namespace }}.svc.cluster.local
  http:
  - route:
    - destination:
        host: {{ printf "%s.%s" .Values.serviceName .Values.namespace }}.svc.cluster.local
    retries:
      attempts: {{ .Values.retryPolicy.count | default  3 }}
      perTryTimeout: {{ .Values.retryPolicy.timeout | default 150ms }}
      {{- if .Values.retryPolicy.retryOn }}
      retryOn: {{ .Values.retryPolicy.retryOn }}
      {{- end }}}
---